server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:9999/campus_product?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: SxhSxn5201314
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: campus-product-backend

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dz.campus_product_backend.entity

